<a href="https://colab.research.google.com/github/Mahmoudamin11/Pytorch-Learn-CNN/blob/main/tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch

In [27]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_tensor = my_tensor.reshape(-1 , 2)
my_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [29]:
my_tensor2 = my_tensor.reshape(2, -1)
print("Tensor 2")
my_tensor2

Tensor 2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
my_tensor[1] = 4141
my_tensor

tensor([[   0,    1],
        [4141, 4141],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [31]:
print("Tensor 2")
my_tensor2

Tensor 2


tensor([[   0,    1, 4141, 4141,    4],
        [   5,    6,    7,    8,    9]])

In [48]:
# grabbing specific item not returning a number -> tensor(number)
tsn = torch.arange(10)
# tsn[7] #  tensor(7)
tsn = tsn.reshape(-1, 2)
tsn

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [50]:
tsn2 = torch.arange(10)
tsn2 = tsn2.reshape(-1, 2)
tsn2 = tsn2[:, 1:] # slicing
# u don't have to do so cause it was already as a vector before slicing
# tsn = tsn.reshape(-1, 1)
tsn2

tensor([[1],
        [3],
        [5],
        [7],
        [9]])