<a href="https://colab.research.google.com/github/Mahmoudamin11/Pytorch-Learn-CNN/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Normal List

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy List -> Default Type = float 64


In [3]:
np1 = np.random.rand(3, 4) # that makes random list 3 Rows X 4 Cols
np1

array([[0.07423562, 0.64676189, 0.42976689, 0.73313533],
       [0.93735858, 0.63365451, 0.28885156, 0.76383304],
       [0.05321525, 0.97205843, 0.02708008, 0.53592959]])

In [4]:
np1.dtype

dtype('float64')

# Tensors -> default data type = float 32

In [5]:
tensor2d = torch.randn(3, 4)
tensor2d

tensor([[-0.3514, -1.0588,  0.4040, -1.6559],
        [-0.6878,  0.8953, -0.5345,  1.3598],
        [-0.0260,  0.0047,  0.0291,  0.8373]])

In [6]:
tensor3d = torch.zeros(2,3,4)
tensor3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# convert numpy array to tensor

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0742, 0.6468, 0.4298, 0.7331],
        [0.9374, 0.6337, 0.2889, 0.7638],
        [0.0532, 0.9721, 0.0271, 0.5359]], dtype=torch.float64)